plugins {
    id "org.sonarqube" version "3.5.0.2730"
    id 'java'
    id "org.jetbrains.kotlin.jvm" version "2.0.21"
    id 'maven-publish'
    id 'idea'
    id 'eclipse'
    id 'war'
}


group = 'org.jpos.template'
version = '2.1.8-SNAPSHOT'
sourceCompatibility = 17
targetCompatibility = 17

repositories {
    mavenCentral()
    maven { url 'https://jpos.org/maven' }
    mavenLocal()
}

dependencies {
    implementation 'org.jpos:jpos:2.1.8-SNAPSHOT'
    // https://mvnrepository.com/artifact/org.apache.poi/poi
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    providedCompile "org.projectlombok:lombok:1.18.30"
    annotationProcessor "org.projectlombok:lombok:1.18.30"
    providedCompile 'com.oracle.database.jdbc:ojdbc10:19.16.0.0'
    implementation 'org.jpos.ee:jposee-dbsupport:2.2.8'
    // https://mvnrepository.com/artifact/jcifs/jcifs
    implementation 'eu.agno3.jcifs:jcifs-ng:2.1.7'

}

tasks.withType(JavaCompile).configureEach {
    options.annotationProcessorPath = configurations.annotationProcessor
}

apply from: 'jpos-app.gradle'

