origin=POSNET
file_server=vdicet005
10_channel_host=localhost


# Base principal Amazon Test
dbhost=awsoraclejpos.desa.cabal.coop
dbname=amazontest
dbuser=SWITCHDESA
dbpass=hnPAitv57desaoSQfwgz
SID=/jposdesa
