channel=B24Channel
packager_channel=GenericPackager

iso_version=iso93ascii
10_channel_host=localhost
10_channel_port=11350



# Base principal Amazon Test
dbhost=awsoraclejpos.desa.cabal.coop
dbname=amazontest
dbuser=SWITCHDESA
dbpass=hnPAitv57desaoSQfwgz
SID=/jposdesa
